version: 1
jobs:
  build:
    docker:
      - image: circleci/node:6-browsers
    steps:
    - checkout
    - run: cd front
    - run:
        name: install-dependencies
        command: yarn install
    - run: npm install -g karma
    - run: npm install karma-jasmine karma-chrome-launcher jasmine-core --save-dev
    - run: npm install -g karma-cli
    - run: karma start
    - run: karma test